"""
Provides functions that save the different data representations to disc

Made by Turidus https://github.com/Turidus/Minecraft-MapMaker
Copyright (c) 2018 Turidus

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


"""

import os
import gzip

import Parsers
import nbt


def saveAmountTxT(mapColorIDMatrix, mapColorIDDic, name):
    """
    This takes a mapColorIDMatrix,  a mapColorID dictionary and  a name string, to save a formated string,
    containing the type and amount of used blocks, to disc.
    
    param:  mapColorIDMatrix: A nested list with mapColorIDs (f.e. [[5, 17, 21, ... ] ... ]
                        
                        First index descripes the X coordinate of the map and image
                        Second index descripes the Z coordinate of the map and the Y value of the image
                        
            mapColorIDDic: A dictionary containing all available mapColorIDs generated by MapColorIDGenerator.py
            
            name: String, will be part of the filename
    """
    
    stringToSave = Parsers.mapColorIDToAmountString(mapColorIDMatrix, mapColorIDDic)
    
    if not os.path.isdir("./save/" + name + "/"):
        
        if not os.path.isdir("./save"):
            os.mkdir("./save/")
        os.mkdir("./save/" + name + "/")
        
    with open("./save/" + name + "/" + name +"_amount.txt", "w") as saveFile:
        saveFile.write(stringToSave)
        
        
        
        
def saveBlockPositionTxT(positionMatrix,mapColorIDDic, name):
    """
    This fuction takes a positionMatrix, a mapColorID dictionary and a name string, to save a string, containing the
    type and position of all used blocks, to disc.
    
    param:  positionMatrix: A nested list with positions (f.e. [[pos, pos, pos, ... ] ... ]
                                Positions are lists with [mapColorID, X, Z, Y], all integers
                        
            mapColorIDDic: A dictionary containing all available mapColorIDs generated by MapColorIDGenerator.py
    
            name: String, will be part of the filename
    """
    
    stringToSave = Parsers.positionMatrixToPositionString(positionMatrix,mapColorIDDic)
    
    if not os.path.isdir("./save/" + name):
        
        if not os.path.isdir("./save"):
            os.mkdir("./save/")
        os.mkdir("./save/" + name + "/")
        
    with open("./save/" + name + "/" + name +"_BlockPositions.txt", "w") as saveFile:
        saveFile.write(stringToSave)
        
        
        
        
def saveImage(mapColorIDMatrix, mapColorIDDic, name):
    """
    This takes a mapColorIDMatrix, a mapColorID dictionary and a name, to save a image file,
    containing a preview of the map, to disc.
    
    param:  mapColorIDMatrix: A nested list with mapColorIDs (f.e. [[5, 17, 21, ... ] ... ]
                        
                        First index descripes the X coordinate of the map and image
                        Second index descripes the Z coordinate of the map and the Y value of the image
                        
            mapColorIDDic: A dictionary containing all available mapColorIDs generated by MapColorIDGenerator.py
            
            name: String, will be part of the filename
    

    """
    
    imageToSave = Parsers.mapColorIDToPicture(mapColorIDMatrix, mapColorIDDic)
    
    if not os.path.isdir("./save/" + name):
        
        if not os.path.isdir("./save"):
            os.mkdir("./save/")
        os.mkdir("./save/" + name + "/")
    
    with open("./save/" + name + "/" + name +"_endresult.bmp", "wb") as saveFile:
        
        imageToSave.save(saveFile, format = "BMP")
        
        
        
        
def saveSchematic(Tag_Compound_List, name):
    """
    This takes a list of Tag_Compounds and a name string and saves a schematic file for every Tag_Compound in the list.

    
    param:  Tag_Compound_List: A list of Tag_Compounds.
            
            name: String, will be part of the filename
    

    """
    
    if not os.path.isdir("./save/" + name):
        
        if not os.path.isdir("./save"):
            os.mkdir("./save/")
        os.mkdir("./save/" + name + "/")
    
    if len(Tag_Compound_List) == 1:
        Tag_Compound_List[0].name = "Schematic"
        schematicToSave = gzip.compress(nbt.toByte(Tag_Compound_List[0]))
            
        with open("./save/" + name + "/" + name +".schematic", "wb") as saveFile:
            
            saveFile.write(schematicToSave)
            
    else:
        for index in range(len(Tag_Compound_List)):
            
            tempTag_Compound = Tag_Compound_List[index]
            partNumber = tempTag_Compound.name.split()
            tempTag_Compound.name = "Schematic"
            
            schematicToSave = gzip.compress(nbt.toByte(Tag_Compound_List[index]))
                
            with open("./save/" + name + "/" + name +"partX{}Z{}.schematic".format(partNumber[0],partNumber[1]), "wb") as saveFile:
                
                saveFile.write(schematicToSave)
    
    
    